// <auto-generated />
using System;
using Backend_APIs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_APIs.Migrations
{
    [DbContext(typeof(MediaidbContext))]
    [Migration("20260518153000_AddFeedbacksTable")]
    partial class AddFeedbacksTable
    {
    }
}